
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 17 17:39:20 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 7;
  public static final int SEMICOLON = 16;
  public static final int CHAR = 19;
  public static final int IN = 6;
  public static final int RCURLY = 15;
  public static final int RROUND = 13;
  public static final int WRITE = 8;
  public static final int ID = 3;
  public static final int SUB = 24;
  public static final int LCURLY = 14;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int DIV = 22;
  public static final int LROUND = 12;
  public static final int ADD = 23;
  public static final int LSQUARE = 10;
  public static final int CONST = 4;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int RSQUARE = 11;
  public static final int INTEGER = 18;
  public static final int FOR = 5;
  public static final int REAL = 20;
  public static final int MUL = 21;
}

